# Production configuration
# Override any development-specific settings here

# Ensure proper URL and baseurl for production
url: "https://davidlxu.github.io"
baseurl: ""

# Disable development-specific features
future: false
show_excerpts: true

# Optimize for production
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  profile: false
  startings: [html, head, body] 